version: '3'

services:
    postgres:
        image: postgres
        container_name: postgres
        networks:
        - mynet
        environment:
        POSTGRES_PASSWORD: password
        ports:
        - 5432:5432

    mongodb:
        image: mongo
        container_name: mongodb
        networks:
        - mynet
        environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
        ports:
        - 27017:27017

    rabbitmq:
        image: rabbitmq:3.8.2-management
        ports:
        - \"5672:5672\"
        - \"15672:15672\"
        networks:
        - mynet
    redis:
        image: redis:5.0.5
        ports:
        - \"6379:6379\"
        networks:
        - mynet

networks:
  mynet:
    driver: bridge
