FROM python:3.10
LABEL Phan <phannt1@vmodev.com>

COPY . /src

# RUN virtualenv .venv
RUN pip install pipenv
RUN pipenv install --ignore-pipfile

EXPOSE 8000

WORKDIR /src

CMD ["sanic", "main.app"]